### ISSUE TITLE
Error en Orden FILLED

### ISSUE THREAD

**Issue by geikon** [matiasdamelio/ROFEX_FIX#1]
Estoy obteniendo este mensaje cuando una orden se completa:

20200707-18:48:27.000000000 : 8=FIXT.1.19=29135=834=1149=ROFX52=20200707-18:48:27.54456=gdgiron19011=REM19016=65785.00011=jDrwx8cGrthgU2FD14=117=T698682331=6578532=137=18438080438=139=240=244=6578554=255=RFX20Sep2058=Operada 59=060=20200707-18:48:27.467150=F151=0207=ROFX453=1448=matriz_remarkets447=D452=1110=176

20200707-18:48:27.000000000 : 8=FIXT.1.19=12835=j34=449=gdgiron190152=20200707-18:48:27.00056=ROFX45=1158=Conditionally Required Field Missing (41)372=8380=51137=910=043

20200707-18:48:27.000000000 : 8=FIXT.1.19=12635=334=1249=ROFX52=20200707-18:48:27.58456=gdgiron190145=458=Tag not defined for this message type371=1137372=j373=210=171

Que puede estar sucediendo?

**Comment by matiasdamelio** [comment]
@geikon disculpa la demora, no se si ya pudiste resolverlo. 

El primer error que tira es un BusinessMessageReject, haciendo referencia al Tag 41 que es el OrigClOrdID. En /Main/application.py, en la función **onMessage_ExecutionReport_OrderFilledPartiallyFilledResponse** se pide el valor de ese Tag y al no encontrarlo en el mensaje de FIX, devuelve ese error. 

El segundo error que tira es un Reject, consecuencia del BusinessMessageReject. Por lo tanto, al no tener el primero, no deberia aparecer el segundo. Igualmente la forma de arreglarlo creo que es la siguiente (no lo testee):

En /conf/spec/FIX50SP2_rofex.xml hay que agregar:

- `<field number="1137" name="DefaultApplVerID" type="STRING" />`

- Buscar 
`<message name="BusinessMessageReject" msgtype="j" msgcat="app">
            <field name="RefSeqNum" required="N" />
            <field name="RefMsgType" required="Y" />
            <field name="RefApplVerID" required="N" />
            <field name="RefApplExtID" required="N" />
            <field name="RefTagID" required="N" />
            <field name="RefCstmApplVerID" required="N" />
            <field name="BusinessRejectRefID" required="N" />
            <field name="BusinessRejectReason" required="Y" />
            <field name="Text" required="N" />
            <field name="EncodedTextLen" required="N" />
            <field name="EncodedText" required="N" />
        </message>` 
y agregar 
`<field name="DefaultApplVerID" required="N" />`

**Comment by geikon** [comment]
Gracias por la ayuda , lo había resuelto modificando application.py por que ese mensaje lo recibia cuando creaba  una new order y por lo tanto me parecía que no correspondía  el tag OrigClOrdID.
De todas formas voy a a probar modificando el diccionario de definiciones tal cual lo proponés.
Te quiero felicitar y agradecer por el laburo de difusión que haces con estos fuentes ya que es muy dificil de encontrar información clara sobre FIX. En mi caso fue una ayuda gigante para mi proyecto.

**Comment by matiasdamelio** [comment]
Genial que lo hayas resuelto!
Sí, lo del diccionario es mas que nada prueba y error muchas veces.
Muchas gracias! Sí, justamente ese fue el problema con el cual me encontré cuando empecé con FIX. La mayoría de las veces solamente encontras los ROES, pero nada de como realmente hacer la conexión.
